server:
  port: 9999
spring:
  profiles:
    active: ${config.env}
  redis:
    host: 127.0.0.1
    port: 6379
    password: "@wecredo2016"
    client-name: redis-client
    lettuce:
      shutdown-timeout: 300ms
      pool:
        min-idle: 1
        max-active: 10
        max-idle: 10
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: sunyilo@163.com
    password: BVPJGAZTCGDVPVCX
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    name: rearwave
    url:  jdbc:mysql://127.0.0.1:3306/rearwave?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      validation-query: SELECT 'X'
      default-auto-commit: true
      query-timeout: 30000
      min-idle: 5
      max-active: 30
      name: rear-wave
      initial-size: 3
      kill-when-socket-read-timeout: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB  #设置支持的单个上传文件大小
      max-request-size: 200MB  #设置最大的请求文件大小，设置总体大小的请求
      file-size-threshold: 10MB #当上传文件达到指定配置量的时候，会将文件内容写入到磁盘
      location: /mnt/upload/tmp   #设置上传文件的临时目录

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.rearwave.blog.*.model
  global-config:
    #数据库大写下划线转换
    capital-mode: false
    #删除
    logic-delete-value: 1
    #不删除
    logic-not-delete-value: 0
    #动态刷新mapper
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
debug: true
